# Generated by Django 2.0.5 on 2018-05-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initiative_modifier', models.IntegerField(default=0)),
                ('perception_modifier', models.IntegerField(default=0)),
                ('armor_class', models.IntegerField(default=10)),
                ('hit_points', models.IntegerField(default=0)),
                ('cmd', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'encounter',
            },
        ),
        migrations.CreateModel(
            name='EncounterCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField(default=0)),
                ('delaying', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Encounter')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ended', models.BooleanField(default=False)),
                ('slack_channel', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_id', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='gm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Player'),
        ),
        migrations.AddField(
            model_name='encountercharacters',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Player'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Game'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Player'),
        ),
    ]
