# Generated by Django 2.0.5 on 2018-05-12 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'adjustments',
            },
        ),
        migrations.CreateModel(
            name='GameAdjustments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_round', models.IntegerField(default=0)),
                ('end_round', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'game_adjustments',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='fortitude_save',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='reflex_save',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='will_save',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encountercharacters',
            name='start_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='encountercharacters',
            table='encounter_characters',
        ),
        migrations.AddField(
            model_name='gameadjustments',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gm.Character'),
        ),
        migrations.AddField(
            model_name='gameadjustments',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gm.Encounter'),
        ),
        migrations.AddField(
            model_name='gameadjustments',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Game'),
        ),
    ]
