# Generated by Django 2.0.5 on 2018-05-06 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Player')),
                ('player_characters', models.ManyToManyField(related_name='game_player_characters', related_query_name='player_characters', to='gm.PlayerCharacter')),
                ('players', models.ManyToManyField(related_name='game_players', related_query_name='players', to='gm.Player')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
