# Generated by Django 2.0.5 on 2018-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='slack_channel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
