# Generated by Django 2.0.5 on 2018-05-12 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0002_auto_20180512_0345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adjustments',
            new_name='Adjustment',
        ),
        migrations.AddField(
            model_name='gameadjustments',
            name='adjustment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gm.Adjustment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='me', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='adjustment',
            table='adjustment',
        ),
    ]
