# Generated by Django 2.0.5 on 2018-05-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0002_auto_20180514_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='ended',
        ),
        migrations.AddField(
            model_name='encounter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encountercharacter',
            name='last_acted',
            field=models.IntegerField(default=-1),
        ),
    ]
