# Generated by Django 2.0.5 on 2018-05-15 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0003_auto_20180514_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-encounter_time']},
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='first_round',
            new_name='round',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_round',
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounter_time',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
