# Generated by Django 2.0.5 on 2018-05-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0004_auto_20180512_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Game')),
            ],
            options={
                'db_table': 'game_characters',
            },
        ),
    ]
