# Generated by Django 2.0.5 on 2018-05-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0006_auto_20180512_0904'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='encountercharacter',
            table='encounter_character',
        ),
        migrations.AlterModelTable(
            name='gameadjustment',
            table='game_adjustment',
        ),
        migrations.AlterModelTable(
            name='gamecharacter',
            table='game_character',
        ),
    ]
