# Generated by Django 2.0.5 on 2018-05-14 06:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'adjustment',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('statblock', models.TextField()),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ended', models.BooleanField(default=False)),
                ('first_round', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'encounter',
            },
        ),
        migrations.CreateModel(
            name='EncounterCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField(default=0)),
                ('delaying', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Encounter')),
            ],
            options={
                'db_table': 'encounter_character',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('slack_channel', models.CharField(max_length=20)),
                ('current_round', models.IntegerField(default=0)),
                ('characters', models.ManyToManyField(to='game.Character')),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='GameAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_round', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=1)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Adjustment')),
                ('characters', models.ManyToManyField(to='game.Character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='game.Character')),
            ],
            options={
                'db_table': 'game_adjustment',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='gm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='characters',
            field=models.ManyToManyField(through='game.EncounterCharacter', to='game.Character'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
    ]
