# Generated by Django 2.0.5 on 2018-05-20 02:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={},
        ),
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
        migrations.AlterField(
            model_name='character',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, editable=False),
        ),
    ]
