# Generated by Django 2.0.5 on 2018-05-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180520_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
