# Generated by Django 2.0.5 on 2018-05-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='npc',
            field=models.BooleanField(default=False),
        ),
    ]
